# Generated by Django 2.0.5 on 2020-08-26 11:30

import datetime
from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('full_name', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=10, validators=[orders.validators.validate_number])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('completed', models.BooleanField(default=False)),
                ('date_ordered', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
